In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split

In [2]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn import linear_model
from sklearn import tree
from sklearn.neural_network import MLPRegressor

from sklearn.metrics import mean_squared_error

In [3]:
data = pd.read_csv("data/cleaned_data.csv")
data.head()

,Unnamed: 0,ID,Confirmed,Deaths,Recovered,Active,Incident_Rate,People_Tested,People_Hospitalized,Mortality_Rate,...,State_Utah,State_Vermont,State_Virginia,State_Washington,State_West Virginia,State_Wisconsin,State_Wyoming,Day,Month,Year
0,0,0,3563,93,NaN,3470.0,75.988020,21583.0,437.0,2.610160,...,0,0,0,0,0,0,0,8,31,20
1,1,1,272,8,66.0,264.0,45.504049,8038.0,31.0,2.941176,...,0,0,0,0,0,0,0,8,31,20
2,2,2,3542,115,NaN,3427.0,48.662422,42109.0,NaN,3.246753,...,0,0,0,0,0,0,0,8,31,20
3,3,3,1280,27,367.0,1253.0,49.439423,19722.0,130.0,2.109375,...,0,0,0,0,0,0,0,8,31,20
4,4,4,22795,640,NaN,22155.0,58.137726,190328.0,5234.0,2.812020,...,0,0,0,0,0,0,0,8,31,20

In [4]:
data.isna().sum()

Unnamed: 0            0
ID                    0
Confirmed             0
Deaths                0
Recovered          1329
                   ...
State_Wisconsin       0
State_Wyoming         0
Day                   0
Month                 0
Year                  0
Length: 65, dtype: int64

In [5]:
X = data.drop(columns=["Confirmed", "Deaths"])
y = data['Deaths']

#dropped features with missing data for now
X.drop(columns = ["Recovered", "People_Hospitalized", "Hospitalization_Rate"], inplace = True)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

In [6]:
model = linear_model.LinearRegression()
model = tree.DecisionTreeRegressor()
model = KNeighborsRegressor()
model = MLPRegressor(solver='adam', alpha=0.01, hidden_layer_sizes=(100), random_state=0, max_iter=1000)
model = RandomForestRegressor()

In [7]:
model.fit(X_train, y_train)
pred = model.predict(X_train)
rmse_train = mean_squared_error(pred, y_train) ** 0.5
pred = model.predict(X_test)
rmse_test = mean_squared_error(pred, y_test) ** 0.5

rmse_train, rmse_test

(38.73982245059367, 89.14261149187602)